name: Generate Keystore
on:
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair -v \
            -keystore my-upload-key.jks \
            -alias upload \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "${{ secrets.KS_TEMP_PASS }}" \
            -keypass "${{ secrets.KS_TEMP_PASS }}" \
            -dname "CN=SheetOn, OU=Dev, O=Studio1111, L=Tehran, ST=Tehran, C=IR"
      - uses: actions/upload-artifact@v4
        with:
          name: release-keystore
          path: my-upload-key.jks
